services:
  api:
    build: ./backend
    entrypoint: ["/bin/bash", "entrypoint.sh"]
    command: ["gunicorn", "kogui_pokedex.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "60"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://localhost:80"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped
